quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=prodavnica_user
quarkus.datasource.password=prodavnica123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/online_prodavnica

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true